### ISSUE TITLE
Is Titan still under developing?

### ISSUE THREAD

**Issue by acelyc111** [tikv/rocksdb#233]
We want to use [Titan](https://github.com/tikv/rocksdb/tree/titan-5.15) to some other storage system, is it still under developing? Is it stable enough to use it on production environment?
Thanks!

**Comment by Connor1996** [comment]
It's stable to use in production. But some performance improvements, such as level-merge and gc-rewrite-merge are still experimental now (disabled by default)

**Comment by acelyc111** [comment]
@Connor1996 Thanks!
