### ISSUE TITLE
How about the performence on hdd

### ISSUE THREAD

**Issue by ncuwaln** [tikv/rocksdb#261]
How about the performence on hdd, can you give some performence data about titan on hdd ? thanks

**Comment by tabokie** [comment]
Sorry, AFAIK we haven't done any benchmarks on HDD.

The RocksDB was originally designed for "fast storage", so is TiKV and its components. So it's unlikely for us to allocate extra resource to run a HDD bench any time soon.

**Comment by ncuwaln** [comment]
> Sorry, AFAIK we haven't done any benchmarks on HDD.
> 
> The RocksDB was originally designed for "fast storage", so is TiKV and its components. So it's unlikely for us to allocate extra resource to run a HDD bench any time soon.

Sad, but thanks a lot. we will run a HDD benchmarks
