### ISSUE TITLE
Upgrade to facebook 6.29

### ISSUE THREAD

**Issue by tabokie** [tikv/rocksdb#277]
Reason for 6.29:
- Version above 6.27 has superior performance (especially read) according to [official benchmarks](https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks)
- Not sure about facebook's backport policy, but 6.29 is getting more minor releases than predecessors

List of TiKV patches in chronological order:
- [x] https://github.com/tikv/rocksdb/commit/a29144f8e992c36f429d74603c43cb22fbead616: https://github.com/tikv/rocksdb/pull/116
- https://github.com/tikv/rocksdb/commit/9c5b744ee4b2f750570a5153d62b0fac7444d920: https://github.com/tikv/rocksdb/pull/123
- [x] https://github.com/tikv/rocksdb/commit/9ab5a5f9e70d2ea5fc9bd22a455d52a5d082fd57: https://github.com/tikv/rocksdb/pull/126
- https://github.com/tikv/rocksdb/commit/4dcfb87891b4176fc4b17a24c16a235cc2e40f82: https://github.com/tikv/rocksdb/pull/140
- [x] https://github.com/tikv/rocksdb/commit/ebec1bd8a0f3bc81782e917fe8019c4d17f332a3: https://github.com/tikv/rocksdb/pull/131
- [x] https://github.com/tikv/rocksdb/commit/c7d775168d1f4b81c5f185d9c41a999108150389: https://github.com/tikv/rocksdb/pull/136
- https://github.com/tikv/rocksdb/commit/77a354652d6e178a43b30508494b27cf4c0f072a: https://github.com/tikv/rocksdb/pull/148
- https://github.com/tikv/rocksdb/commit/96d7d163ab40c6f7122605f3705c4407e12d6fe1: https://github.com/tikv/rocksdb/pull/147
- https://github.com/tikv/rocksdb/commit/17aa69c290ed2b870e2361b4a00795d1d68e9ccb: https://github.com/tikv/rocksdb/pull/150
- [x] https://github.com/tikv/rocksdb/commit/906258cb21d221162dd9047e2753237d7070fb34: https://github.com/tikv/rocksdb/pull/153
- [x] https://github.com/tikv/rocksdb/commit/113b3638179107fbf886aade14430f8ec5714f5a: https://github.com/tikv/rocksdb/pull/151
- [x] https://github.com/tikv/rocksdb/commit/2938ac580a16995fa57f390b5bb55502614c567c: https://github.com/tikv/rocksdb/pull/154
- [x] https://github.com/tikv/rocksdb/commit/aa67f5c852a4104a7ce50898aa9d33393d66aecc: https://github.com/tikv/rocksdb/pull/155
- [x] https://github.com/tikv/rocksdb/commit/3d44a33f6e08fbf4cc5a102fd17e88fc674dcc8d: https://github.com/tikv/rocksdb/pull/156
- [x] https://github.com/tikv/rocksdb/commit/23605627930ad51ff57ec2f005481b9b905cc9a3: https://github.com/tikv/rocksdb/pull/167
- [x] https://github.com/tikv/rocksdb/commit/6e7abd550a119d8c302dc11282312292e682f4d4: https://github.com/tikv/rocksdb/pull/170
- [x] https://github.com/tikv/rocksdb/commit/991bb28797568fee037dbaf5a1b467d1e54b0ac3: https://github.com/tikv/rocksdb/pull/171
- [x] https://github.com/tikv/rocksdb/commit/bf9fa0eb8e6fe10ccc4c50a9e87acde4aacb17d2: https://github.com/tikv/rocksdb/pull/160
- [x] https://github.com/tikv/rocksdb/commit/f114e1361188c41f7612ba7ee575d02b88dbd80c: https://github.com/tikv/rocksdb/pull/181
- [x] https://github.com/tikv/rocksdb/commit/9b549268cf61b7e1a90402f4f3c2b3cb442cd925: https://github.com/tikv/rocksdb/pull/177
- https://github.com/tikv/rocksdb/commit/c1178cda46770ca1e02b9fc304aa7df2338c4d5d: https://github.com/tikv/rocksdb/pull/189
- https://github.com/tikv/rocksdb/commit/cb1a5622f3886be2047b688981d01916af8da4c7: https://github.com/tikv/rocksdb/pull/194
- https://github.com/tikv/rocksdb/commit/953f8b2f23eabdc0df9adb4fc50b566ae0c5a5e9: https://github.com/tikv/rocksdb/pull/195
- [x] https://github.com/tikv/rocksdb/commit/cf6a77d9ba13de8df8f374d87c9fbfc7003c4f52: https://github.com/tikv/rocksdb/pull/193
- [x] https://github.com/tikv/rocksdb/commit/1a0b394fef8f8e0ec8fc8c45938d1913730c8cef: https://github.com/tikv/rocksdb/pull/200
- [x] https://github.com/tikv/rocksdb/commit/6251283442ff3a69ed7f9c4ab3ef8fc62197d1c0: https://github.com/tikv/rocksdb/pull/202
- [x] https://github.com/tikv/rocksdb/commit/0a4d235313a661916e3b5066dac76fe6c5608d7e: https://github.com/tikv/rocksdb/pull/192
- https://github.com/tikv/rocksdb/commit/11df16b3039a2a414c9c57957a59274474e0fa39: https://github.com/tikv/rocksdb/pull/205
- [x] https://github.com/tikv/rocksdb/commit/7093ba380dd51970912610eff384702272f1e17f: https://github.com/tikv/rocksdb/pull/211
- [x] https://github.com/tikv/rocksdb/commit/355b496bf9d78d2f52e4972ec22cc9d35c234275: https://github.com/tikv/rocksdb/pull/207
- [x] https://github.com/tikv/rocksdb/commit/fbbe2c873da2319c8986cb315f7ea8e75553a79c: https://github.com/tikv/rocksdb/pull/215
- [x] https://github.com/tikv/rocksdb/commit/4b0908b9d9620acbef4ed2003ac5868332c90897: https://github.com/tikv/rocksdb/pull/217
- [x] https://github.com/tikv/rocksdb/commit/7d209a859fbfed6095b3df9cf2a33fdd8056527b: https://github.com/tikv/rocksdb/pull/213
- [x] https://github.com/tikv/rocksdb/commit/93e89a58edb820f2daa15362120617e49ef6ddd6: https://github.com/tikv/rocksdb/pull/222
- [x] https://github.com/tikv/rocksdb/commit/a487d256ee927afc17ffe2dd863e4769c4ae8f3b: https://github.com/tikv/rocksdb/pull/216
- [x] https://github.com/tikv/rocksdb/commit/2dfbfa51b7892a80debc18e52c863b93bd79e491: https://github.com/tikv/rocksdb/pull/218
- [x] https://github.com/tikv/rocksdb/commit/00874ebfb608016df966225e922078a8f2df3fd1: https://github.com/tikv/rocksdb/pull/224
- https://github.com/tikv/rocksdb/commit/0b76f875f72ce22c683042ca6b61d388c3a2ee9d: https://github.com/tikv/rocksdb/pull/219
- [x] https://github.com/tikv/rocksdb/commit/0d1ac74cce5397485d8d132cbcd5ba702a578925: https://github.com/tikv/rocksdb/pull/226
- [x] https://github.com/tikv/rocksdb/commit/5d559f08a5dd24c2d814d873d30ee4842ebc2d20: https://github.com/tikv/rocksdb/pull/227
- https://github.com/tikv/rocksdb/commit/58c0ecbc4e1ee5a3fee96f8c37f9312f782ce717: https://github.com/tikv/rocksdb/pull/236
- [x] https://github.com/tikv/rocksdb/commit/a2b20bddc303e5ac6fc75ebf657944307c4e2bc9: https://github.com/tikv/rocksdb/pull/241
- [x] https://github.com/tikv/rocksdb/commit/b22a85a74dd7b1a9c00410fdaf0732d70fefdc46: https://github.com/tikv/rocksdb/pull/247
- [x] https://github.com/tikv/rocksdb/commit/f95aaf8dac667334bb6314bd06d80749f63177bb: https://github.com/tikv/rocksdb/pull/251
- [x] https://github.com/tikv/rocksdb/commit/3de4cc218406258204579ef1f3ef109d2b8e9390: https://github.com/tikv/rocksdb/pull/237
- https://github.com/tikv/rocksdb/commit/6b97c0567c4694ef1d06374d54bf582e541d215d: https://github.com/tikv/rocksdb/pull/250
- [x] https://github.com/tikv/rocksdb/commit/b071c44789fd21f3bce10bcf5e8c4224c7c0703b: https://github.com/tikv/rocksdb/pull/234
- [x] https://github.com/tikv/rocksdb/commit/d822f13d89fb2df384d71fb86c5a9123cb0d7c33: https://github.com/tikv/rocksdb/pull/257
- https://github.com/tikv/rocksdb/commit/24213c4086d4daaf26aee29663c47438890e1a2e: https://github.com/tikv/rocksdb/pull/255
- https://github.com/tikv/rocksdb/commit/f236fe443d06337ca2538414c62f70ba17b8e409: https://github.com/tikv/rocksdb/pull/256
- [x] https://github.com/tikv/rocksdb/commit/21712fe4243a57a5e7854574b933e67d0fd227f6: https://github.com/tikv/rocksdb/pull/267
- [x] https://github.com/tikv/rocksdb/commit/9dcc3336ade4ae2515f9342c419a17180cc6fc54: https://github.com/tikv/rocksdb/pull/272
- [x] https://github.com/tikv/rocksdb/commit/61b0e36d31a370c6f7c69549fea4547457b97819: https://github.com/tikv/rocksdb/pull/275

Bullet-ed items are not cherry-picked, for either one of these reasons:
- Build related
- Already deprecated in 6.4.tikv (e.g. multi batch write)
- Rendered unnecessary by new improvements from 6.29.fb (consistency check and cache key collision)

**Comment by hunterlxt** [comment]
Are you going to pick our commits to 6.29? In what TiKV version are we going to start using 6.29?

**Comment by tabokie** [comment]
@hunterlxt Soon I hope. Both multi-rocksdb and user timestamp require a newer version of RocksDB.

**Comment by tabokie** [comment]
A list of facebook features that might interact with our old codebase, needs further scrutiny:
- https://github.com/facebook/rocksdb/pull/8602
- https://github.com/facebook/rocksdb/pull/5761

**Comment by hunterlxt** [comment]
I found in v6.29 blobdb is introduced(`rocksdb_options_set_enable_blob_files`), maybe we can do some bench. cc @Connor1996

**Comment by Connor1996** [comment]
blobdb has been already introduced before @hunterlxt

**Comment by hunterlxt** [comment]
> blobdb has been already introduced before @hunterlxt

But I don't find any FFI to `rocksdb_options_set_enable_blob_files` in rust-rocksdb

**Comment by BusyJay** [comment]
Why https://github.com/tikv/rocksdb/pull/147 is not picked?

**Comment by tabokie** [comment]
@BusyJay The feature is removed in case you forgot: https://github.com/tikv/titan/pull/249
