### ISSUE TITLE
What's the status of SPDK integration?

### ISSUE THREAD

**Issue by cannium** [tikv/rocksdb#351]
I read about the SPDK integration article https://www.pingcap.com/blog/tikv-and-spdk-pushing-the-limits-of-storage-performance/ and wondering about the current status of tikv with SPDK. Have you successfully integrated SPDK into tikv? If not, what problems you met, is there a schedule?

**Comment by Connor1996** [comment]
Sorry, no further progress just because it's not of high priority.

**Comment by cannium** [comment]
So sad. Reading from the article, the performance gain seems to be real. I'll try to take my own way to integrate spdk, and if I get lucky, I'll make a merge request.
